In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
names = ['age','workclass','fnlwgt','education','education-num','marital-status' ,  'occupation','relationship','race','sex',
'capital-gain','capital-loss','hours-per-week','native-country','income']
df_train = pd.read_csv('adult.data.txt',index_col=False,delim_whitespace=True,names=names,na_values='?')
df_test = pd.read_csv('adult_test.txt',index_col=False,delim_whitespace=True,names=names,na_values='?')
df_train.dropna()
df_test.dropna()

age         workclass  fnlwgt     education  education-num  \
0       25           Private  226802          11th              7   
1       38           Private   89814       HS-grad              9   
2       28         Local-gov  336951    Assoc-acdm             12   
3       44           Private  160323  Some-college             10   
5       34           Private  198693          10th              6   
7       63  Self-emp-not-inc  104626   Prof-school             15   
8       24           Private  369667  Some-college             10   
9       55           Private  104996       7th-8th              4   
10      65           Private  184454       HS-grad              9   
11      36       Federal-gov  212465     Bachelors             13   
12      26           Private   82091       HS-grad              9   
14      48           Private  279724       HS-grad              9   
15      43           Private  346189       Masters             14   
16      20         State-gov  444554  Some-college             10   
17      43           Private  128354       HS-grad              9   
18      37           Private   60548       HS-grad              9   
20      34           Private  107914     Bachelors             13   
21      34           Private  238588  Some-college             10   
23      25           Private  220931     Bachelors             13   
24      25           Private  205947     Bachelors             13   
25      45  Self-emp-not-inc  432824       HS-grad              9   
26      22           Private  236427       HS-grad              9   
27      23           Private  134446       HS-grad              9   
28      54           Private   99516       HS-grad              9   
29      32  Self-emp-not-inc  109282  Some-college             10   
30      46         State-gov  106444  Some-college             10   
31      56  Self-emp-not-inc  186651          11th              7   
32      24  Self-emp-not-inc  188274     Bachelors             13   
33      23         Local-gov  258120  Some-college             10   
34      26           Private   43311       HS-grad              9   
...    ...               ...     ...           ...            ...   
16248   25           Private  242136       HS-grad              9   
16249   31           Private  112115       HS-grad              9   
16250   49      Self-emp-inc   77132       HS-grad              9   
16252   60           Private  117909     Assoc-voc             11   
16253   39           Private  229647     Bachelors             13   
16254   38           Private  149347       Masters             14   
16255   43         Local-gov   23157       Masters             14   
16256   23           Private   93977       HS-grad              9   
16257   73      Self-emp-inc  159691  Some-college             10   
16258   35           Private  176967  Some-college             10   
16259   66           Private  344436       HS-grad              9   
16260   27           Private  430340  Some-college             10   
16261   40           Private  202168   Prof-school             15   
16262   51           Private   82720       HS-grad              9   
16263   22           Private  269623  Some-college             10   
16264   64  Self-emp-not-inc  136405       HS-grad              9   
16266   55           Private  224655       HS-grad              9   
16267   38           Private  247547     Assoc-voc             11   
16268   58           Private  292710    Assoc-acdm             12   
16269   32           Private  173449       HS-grad              9   
16270   48           Private  285570       HS-grad              9   
16271   61           Private   89686       HS-grad              9   
16272   31           Private  440129       HS-grad              9   
16273   25           Private  350977       HS-grad              9   
16274   48         Local-gov  349230       Masters             14   
16275   33           Private  245211     Bachelors             13   
16276

In [3]:
from sklearn.preprocessing import LabelEncoder
# Hint: Now use a for loop over the elements in `le_category` and update df_le #TODO
encoder = LabelEncoder()

ohc_category = ['workclass', 'relationship' 
                 ,'native-country','occupation']
le_category=['sex','income','education','race','marital-status']

df_ohc_train = pd.get_dummies(df_train,columns=ohc_category) 
df_ohc_test = pd.get_dummies(df_test,columns=ohc_category) 


df_le_train = df_ohc_train.copy()
df_le_test = df_ohc_test.copy()
for i in range (len(le_category)):
    df_le_train[le_category[i]]  =encoder.fit_transform(df_le_train[le_category[i]])
    df_le_test[le_category[i]]  =encoder.fit_transform(df_le_test[le_category[i]])

df_le_test.head(6)

age  fnlwgt  education  education-num  marital-status  race  sex  \
0   25  226802          1              7               4     2    1   
1   38   89814         11              9               2     4    1   
2   28  336951          7             12               2     4    1   
3   44  160323         15             10               2     2    1   
4   18  103497         15             10               4     4    0   
5   34  198693          0              6               4     4    1   

   capital-gain  capital-loss  hours-per-week             ...               \
0             0             0              40             ...                
1             0             0              50             ...                
2             0             0              40             ...                
3          7688             0              40             ...                
4             0             0              30             ...                
5             0             0              30             ...                

   occupation_Farming-fishing  occupation_Handlers-cleaners  \
0                           0                             0   
1                           1                             0   
2                           0                             0   
3                           0                             0   
4                           0                             0   
5                           0                             0   

   occupation_Machine-op-inspct  occupation_Other-service  \
0                             1                         0   
1                             0                         0   
2                             0                         0   
3                             1                         0   
4                             0                         0   
5                             0                         1   

   occupation_Priv-house-serv  occupation_Prof-specialty  \
0                           0                          0   
1                           0                          0   
2                           0                          0   
3                           0                          0   
4                           0                          0   
5                           0                          0   

   occupation_Protective-serv  occupation_Sales  occupation_Tech-support  \
0                           0                 0                        0   
1                           0                 0                        0   
2                           1                 0                        0   
3                           0                 0                        0   
4                           0                 0                        0   
5                           0                 0                        0   

   occupation_Transport-moving  
0                            0  
1                            0  
2                            0  
3                            0  
4                            0  
5                            0  

[6 rows x 79 columns]

In [4]:
X_df_train = np.array(df_le_train.drop(['income'],axis=1))
y_train = np.array(df_le_train['income'])
X_df_test = np.array(df_le_test.drop(['income'],axis=1))
y_test = np.array(df_le_test['income'])

nsamples,nfeatures=X_df_train.shape
print (' number of Train samples:{0} and number of features :{1}'.format(nsamples,nfeatures ))
nsamples,nfeatures=X_df_test.shape
print (' number of Test samples:{0} and number of features :{1}'.format(nsamples,nfeatures ))

 number of Train samples:32560 and number of features :78
 number of Test samples:16281 and number of features :78


In [5]:
Xtr_mean = np.mean(X_df_train,axis=0)
Xtr_std = np.std(X_df_train,axis=0)
Xtr_scale = (X_df_train-Xtr_mean)/Xtr_std[None,:]
Xts_scale = (X_df_test-Xtr_mean[None,:])/Xtr_std[None,:]

In [6]:
from sklearn import svm
C_test= [0.05,0.1,0.5,1,5]
gam_test = [0.001,0.005,0.01,0.05,0.1]
nC = len(C_test)
ngam = len(gam_test)
acc = np.zeros((nC,ngam))
for i,c in enumerate(C_test):
    for j,g in enumerate(gam_test):
        svc = svm.SVC(probability=False,  kernel="rbf", C=c, gamma=g,verbose=11)
        svc.fit(Xtr_scale,y_train)
        yhat_ts = svc.predict(Xts_scale)
        acc[i,j]=np.mean(yhat_ts == y_test)

[LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM]

In [7]:
print(acc)

[[0.79816965 0.84085744 0.84208587 0.8312143  0.81960568]
 [0.83373257 0.84343714 0.84503409 0.8381549  0.82740618]
 [0.84902647 0.85123764 0.8522818  0.84613967 0.84024323]
 [0.85129906 0.85412444 0.85510718 0.84810515 0.84294577]
 [0.8540016  0.85412444 0.85203612 0.84515693 0.83803206]]


In [9]:
position=np.argmax(acc)
m, n = divmod(position, 5)
print('greatest accuracy is',acc[m,n])
print('optimal C is',C_test[m])
print('optimal gamma is',gam_test[n])

greatest accuracy is 0.8551071801486395
optimal C is 1
optimal gamma is 0.01


In [10]:
svc = svm.SVC(probability=False,  kernel="rbf", C=1, gamma=0.01,verbose=11)
svc.fit(Xtr_scale,y_train)
yhat_ts = svc.predict(Xts_scale)

[LibSVM]

In [11]:
acc1= np.mean(yhat_ts == y_test)
print('Accuaracy = {0:f}%'.format(100*acc1))
l=0
m=0
n=0
for i in range(y_test.shape[0]):
    if y_test[i]==0:
        l+=1
        if yhat_ts[i]==1:
            m+=1
print('{0:f}% of the people earn less than 50ks are classified as those earn more than 50ks'.format(100*m/l))
print('{0:d} people earn less than 50ks in total in test data'. format(l))
l=0
for i in range(y_test.shape[0]):
    if y_test[i]==1:
        l+=1
        if yhat_ts[i]==0:
            n+=1
print('{0:f}% of the people earn more than 50ks are classified as those earn less than 50ks'.format(100*n/l))
print('{0:d} people earn more than 50ks in total in test data'. format(l))

Accuaracy = 85.510718%
6.151990% of the people earn less than 50ks are classified as those earn more than 50ks
12435 people earn less than 50ks in total in test data
41.445658% of the people earn more than 50ks are classified as those earn less than 50ks
3846 people earn more than 50ks in total in test data
